/*
 * Copyright (C) 2021 University Hospital Bonn - All Rights Reserved You may use, distribute and
 * modify this code under the GPL 3 license. THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT
 * PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR
 * OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
 * IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH
 * YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR
 * OR CORRECTION. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY
 * COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS PERMITTED ABOVE,
 * BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA
 * OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE
 * PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES. You should have received a copy of the GPL 3 license with *
 * this file. If not, visit http://www.gnu.de/documents/gpl-3.0.en.html
 */

package de.ukbonn.mwtek.dashboardlogic.enums;

import de.ukbonn.mwtek.dashboardlogic.tools.CodeUtils;
import java.util.List;

public class AcribisCohortOpsCodes {

  public static final String BYPASS_SURGERY_1 = "5-361";
  public static final String BYPASS_SURGERY_2 = "5-362";
  public static final String ANGIOPLASTY_1 = "8-836.0";
  public static final String ANGIOPLASTY_2 = "8-836.1";
  public static final String ANGIOPLASTY_3 = "8-836.2";
  public static final String CORONARY_ANGIOGRAPHY = "1-275";

  public static final List<String> INCLUSION_CRITERIA_COHORT_3 =
      List.of(
          BYPASS_SURGERY_1,
          BYPASS_SURGERY_2,
          ANGIOPLASTY_1,
          ANGIOPLASTY_2,
          ANGIOPLASTY_3,
          CORONARY_ANGIOGRAPHY);

  // Automatically gathered list of all ops codes via reflection
  public static final List<String> ALL_CODES;

  static {
    ALL_CODES = CodeUtils.extractAllCodes(AcribisCohortOpsCodes.class);
  }
}
